//
//  Icons.h
//  AmazingWeather
//
//  Created by Alexander Shchapov on 9/15/15.
//
//

#ifndef AmazingWeather_Icons_h
#define AmazingWeather_Icons_h

// font properties constants
//#define kTitleFontSize 14
//#define kTitleVerticalOffset

// misc icons
#define kWeatherRefreshIcon [NSString stringWithFormat:@"\uf03e"]
#define kWeatherDefaultIcon [NSString stringWithFormat:@"\uf041"]

// plain codes
#define kOWDWeatherCode200 [NSString stringWithFormat:@"\uf01e"]
#define kOWDWeatherCode201 [NSString stringWithFormat:@"\uf01e"]
#define kOWDWeatherCode202 [NSString stringWithFormat:@"\uf01e"]
#define kOWDWeatherCode210 [NSString stringWithFormat:@"\uf016"]
#define kOWDWeatherCode211 [NSString stringWithFormat:@"\uf016"]
#define kOWDWeatherCode212 [NSString stringWithFormat:@"\uf016"]
#define kOWDWeatherCode221 [NSString stringWithFormat:@"\uf016"]
#define kOWDWeatherCode230 [NSString stringWithFormat:@"\uf01e"]
#define kOWDWeatherCode231 [NSString stringWithFormat:@"\uf01e"]
#define kOWDWeatherCode232 [NSString stringWithFormat:@"\uf01e"]
#define kOWDWeatherCode300 [NSString stringWithFormat:@"\uf01c"]
#define kOWDWeatherCode301 [NSString stringWithFormat:@"\uf01c"]
#define kOWDWeatherCode302 [NSString stringWithFormat:@"\uf019"]
#define kOWDWeatherCode310 [NSString stringWithFormat:@"\uf017"]
#define kOWDWeatherCode311 [NSString stringWithFormat:@"\uf019"]
#define kOWDWeatherCode312 [NSString stringWithFormat:@"\uf019"]
#define kOWDWeatherCode313 [NSString stringWithFormat:@"\uf01a"]
#define kOWDWeatherCode314 [NSString stringWithFormat:@"\uf019"]
#define kOWDWeatherCode321 [NSString stringWithFormat:@"\uf01c"]
#define kOWDWeatherCode500 [NSString stringWithFormat:@"\uf01c"]
#define kOWDWeatherCode501 [NSString stringWithFormat:@"\uf019"]
#define kOWDWeatherCode502 [NSString stringWithFormat:@"\uf019"]
#define kOWDWeatherCode503 [NSString stringWithFormat:@"\uf019"]
#define kOWDWeatherCode504 [NSString stringWithFormat:@"\uf019"]
#define kOWDWeatherCode511 [NSString stringWithFormat:@"\uf017"]
#define kOWDWeatherCode520 [NSString stringWithFormat:@"\uf01a"]
#define kOWDWeatherCode521 [NSString stringWithFormat:@"\uf01a"]
#define kOWDWeatherCode522 [NSString stringWithFormat:@"\uf01a"]
#define kOWDWeatherCode531 [NSString stringWithFormat:@"\uf01d"]
#define kOWDWeatherCode600 [NSString stringWithFormat:@"\uf01b"]
#define kOWDWeatherCode601 [NSString stringWithFormat:@"\uf01b"]
#define kOWDWeatherCode602 [NSString stringWithFormat:@"\uf0b5"]
#define kOWDWeatherCode611 [NSString stringWithFormat:@"\uf017"]
#define kOWDWeatherCode612 [NSString stringWithFormat:@"\uf017"]
#define kOWDWeatherCode615 [NSString stringWithFormat:@"\uf017"]
#define kOWDWeatherCode616 [NSString stringWithFormat:@"\uf017"]
#define kOWDWeatherCode620 [NSString stringWithFormat:@"\uf017"]
#define kOWDWeatherCode621 [NSString stringWithFormat:@"\uf01b"]
#define kOWDWeatherCode622 [NSString stringWithFormat:@"\uf01b"]
#define kOWDWeatherCode701 [NSString stringWithFormat:@"\uf01a"]
#define kOWDWeatherCode711 [NSString stringWithFormat:@"\uf062"]
#define kOWDWeatherCode721 [NSString stringWithFormat:@"\uf0b6"]
#define kOWDWeatherCode731 [NSString stringWithFormat:@"\uf063"]
#define kOWDWeatherCode741 [NSString stringWithFormat:@"\uf014"]
#define kOWDWeatherCode761 [NSString stringWithFormat:@"\uf063"]
#define kOWDWeatherCode762 [NSString stringWithFormat:@"\uf063"]
#define kOWDWeatherCode771 [NSString stringWithFormat:@"\uf011"]
#define kOWDWeatherCode781 [NSString stringWithFormat:@"\uf056"]
#define kOWDWeatherCode800 [NSString stringWithFormat:@"\uf00d"]
#define kOWDWeatherCode801 [NSString stringWithFormat:@"\uf011"]
#define kOWDWeatherCode802 [NSString stringWithFormat:@"\uf011"]
#define kOWDWeatherCode803 [NSString stringWithFormat:@"\uf011"]
#define kOWDWeatherCode804 [NSString stringWithFormat:@"\uf013"]
#define kOWDWeatherCode900 [NSString stringWithFormat:@"\uf056"]
#define kOWDWeatherCode901 [NSString stringWithFormat:@"\uf01d"]
#define kOWDWeatherCode902 [NSString stringWithFormat:@"\uf073"]
#define kOWDWeatherCode903 [NSString stringWithFormat:@"\uf076"]
#define kOWDWeatherCode904 [NSString stringWithFormat:@"\uf072"]
#define kOWDWeatherCode905 [NSString stringWithFormat:@"\uf021"]
#define kOWDWeatherCode906 [NSString stringWithFormat:@"\uf015"]
#define kOWDWeatherCode957 [NSString stringWithFormat:@"\uf050"]

// day codes
#define kOWDDayWeatherCodeCode200 [NSString stringWithFormat:@"\uf010"]
#define kOWDDayWeatherCodeCode201 [NSString stringWithFormat:@"\uf010"]
#define kOWDDayWeatherCodeCode202 [NSString stringWithFormat:@"\uf010"]
#define kOWDDayWeatherCodeCode210 [NSString stringWithFormat:@"\uf005"]
#define kOWDDayWeatherCodeCode211 [NSString stringWithFormat:@"\uf005"]
#define kOWDDayWeatherCodeCode212 [NSString stringWithFormat:@"\uf005"]
#define kOWDDayWeatherCodeCode221 [NSString stringWithFormat:@"\uf005"]
#define kOWDDayWeatherCodeCode230 [NSString stringWithFormat:@"\uf010"]
#define kOWDDayWeatherCodeCode231 [NSString stringWithFormat:@"\uf010"]
#define kOWDDayWeatherCodeCode232 [NSString stringWithFormat:@"\uf010"]
#define kOWDDayWeatherCodeCode300 [NSString stringWithFormat:@"\uf00b"]
#define kOWDDayWeatherCodeCode301 [NSString stringWithFormat:@"\uf00b"]
#define kOWDDayWeatherCodeCode302 [NSString stringWithFormat:@"\uf008"]
#define kOWDDayWeatherCodeCode310 [NSString stringWithFormat:@"\uf008"]
#define kOWDDayWeatherCodeCode311 [NSString stringWithFormat:@"\uf008"]
#define kOWDDayWeatherCodeCode312 [NSString stringWithFormat:@"\uf008"]
#define kOWDDayWeatherCodeCode313 [NSString stringWithFormat:@"\uf008"]
#define kOWDDayWeatherCodeCode314 [NSString stringWithFormat:@"\uf008"]
#define kOWDDayWeatherCodeCode321 [NSString stringWithFormat:@"\uf00b"]
#define kOWDDayWeatherCodeCode500 [NSString stringWithFormat:@"\uf00b"]
#define kOWDDayWeatherCodeCode501 [NSString stringWithFormat:@"\uf008"]
#define kOWDDayWeatherCodeCode502 [NSString stringWithFormat:@"\uf008"]
#define kOWDDayWeatherCodeCode503 [NSString stringWithFormat:@"\uf008"]
#define kOWDDayWeatherCodeCode504 [NSString stringWithFormat:@"\uf008"]
#define kOWDDayWeatherCodeCode511 [NSString stringWithFormat:@"\uf006"]
#define kOWDDayWeatherCodeCode520 [NSString stringWithFormat:@"\uf009"]
#define kOWDDayWeatherCodeCode521 [NSString stringWithFormat:@"\uf009"]
#define kOWDDayWeatherCodeCode522 [NSString stringWithFormat:@"\uf009"]
#define kOWDDayWeatherCodeCode531 [NSString stringWithFormat:@"\uf00e"]
#define kOWDDayWeatherCodeCode600 [NSString stringWithFormat:@"\uf00a"]
#define kOWDDayWeatherCodeCode601 [NSString stringWithFormat:@"\uf0b2"]
#define kOWDDayWeatherCodeCode602 [NSString stringWithFormat:@"\uf00a"]
#define kOWDDayWeatherCodeCode611 [NSString stringWithFormat:@"\uf006"]
#define kOWDDayWeatherCodeCode612 [NSString stringWithFormat:@"\uf006"]
#define kOWDDayWeatherCodeCode615 [NSString stringWithFormat:@"\uf006"]
#define kOWDDayWeatherCodeCode616 [NSString stringWithFormat:@"\uf006"]
#define kOWDDayWeatherCodeCode620 [NSString stringWithFormat:@"\uf006"]
#define kOWDDayWeatherCodeCode621 [NSString stringWithFormat:@"\uf00a"]
#define kOWDDayWeatherCodeCode622 [NSString stringWithFormat:@"\uf00a"]
#define kOWDDayWeatherCodeCode701 [NSString stringWithFormat:@"\uf009"]
#define kOWDDayWeatherCodeCode711 [NSString stringWithFormat:@"\uf062"]
#define kOWDDayWeatherCodeCode721 [NSString stringWithFormat:@"\uf0b6"]
#define kOWDDayWeatherCodeCode731 [NSString stringWithFormat:@"\uf063"]
#define kOWDDayWeatherCodeCode741 [NSString stringWithFormat:@"\uf003"]
#define kOWDDayWeatherCodeCode761 [NSString stringWithFormat:@"\uf063"]
#define kOWDDayWeatherCodeCode762 [NSString stringWithFormat:@"\uf063"]
#define kOWDDayWeatherCodeCode781 [NSString stringWithFormat:@"\uf056"]
#define kOWDDayWeatherCodeCode800 [NSString stringWithFormat:@"\uf00d"]
#define kOWDDayWeatherCodeCode801 [NSString stringWithFormat:@"\uf000"]
#define kOWDDayWeatherCodeCode802 [NSString stringWithFormat:@"\uf000"]
#define kOWDDayWeatherCodeCode803 [NSString stringWithFormat:@"\uf000"]
#define kOWDDayWeatherCodeCode804 [NSString stringWithFormat:@"\uf00c"]
#define kOWDDayWeatherCodeCode900 [NSString stringWithFormat:@"\uf056"]
#define kOWDDayWeatherCodeCode902 [NSString stringWithFormat:@"\uf073"]
#define kOWDDayWeatherCodeCode903 [NSString stringWithFormat:@"\uf076"]
#define kOWDDayWeatherCodeCode904 [NSString stringWithFormat:@"\uf072"]
#define kOWDDayWeatherCodeCode906 [NSString stringWithFormat:@"\uf004"]
#define kOWDDayWeatherCodeCode957 [NSString stringWithFormat:@"\uf050"]

// night codes
#define kOWDNightWeatherCodeCode200 [NSString stringWithFormat:@"\uf02d"]
#define kOWDNightWeatherCodeCode201 [NSString stringWithFormat:@"\uf02d"]
#define kOWDNightWeatherCodeCode202 [NSString stringWithFormat:@"\uf02d"]
#define kOWDNightWeatherCodeCode210 [NSString stringWithFormat:@"\uf025"]
#define kOWDNightWeatherCodeCode211 [NSString stringWithFormat:@"\uf025"]
#define kOWDNightWeatherCodeCode212 [NSString stringWithFormat:@"\uf025"]
#define kOWDNightWeatherCodeCode221 [NSString stringWithFormat:@"\uf025"]
#define kOWDNightWeatherCodeCode230 [NSString stringWithFormat:@"\uf02d"]
#define kOWDNightWeatherCodeCode231 [NSString stringWithFormat:@"\uf02d"]
#define kOWDNightWeatherCodeCode232 [NSString stringWithFormat:@"\uf02d"]
#define kOWDNightWeatherCodeCode300 [NSString stringWithFormat:@"\uf02b"]
#define kOWDNightWeatherCodeCode301 [NSString stringWithFormat:@"\uf02b"]
#define kOWDNightWeatherCodeCode302 [NSString stringWithFormat:@"\uf028"]
#define kOWDNightWeatherCodeCode310 [NSString stringWithFormat:@"\uf028"]
#define kOWDNightWeatherCodeCode311 [NSString stringWithFormat:@"\uf028"]
#define kOWDNightWeatherCodeCode312 [NSString stringWithFormat:@"\uf028"]
#define kOWDNightWeatherCodeCode313 [NSString stringWithFormat:@"\uf028"]
#define kOWDNightWeatherCodeCode314 [NSString stringWithFormat:@"\uf028"]
#define kOWDNightWeatherCodeCode321 [NSString stringWithFormat:@"\uf02b"]
#define kOWDNightWeatherCodeCode500 [NSString stringWithFormat:@"\uf02b"]
#define kOWDNightWeatherCodeCode501 [NSString stringWithFormat:@"\uf028"]
#define kOWDNightWeatherCodeCode502 [NSString stringWithFormat:@"\uf028"]
#define kOWDNightWeatherCodeCode503 [NSString stringWithFormat:@"\uf028"]
#define kOWDNightWeatherCodeCode504 [NSString stringWithFormat:@"\uf028"]
#define kOWDNightWeatherCodeCode511 [NSString stringWithFormat:@"\uf026"]
#define kOWDNightWeatherCodeCode520 [NSString stringWithFormat:@"\uf029"]
#define kOWDNightWeatherCodeCode521 [NSString stringWithFormat:@"\uf029"]
#define kOWDNightWeatherCodeCode522 [NSString stringWithFormat:@"\uf029"]
#define kOWDNightWeatherCodeCode531 [NSString stringWithFormat:@"\uf02c"]
#define kOWDNightWeatherCodeCode600 [NSString stringWithFormat:@"\uf02a"]
#define kOWDNightWeatherCodeCode601 [NSString stringWithFormat:@"\uf0b4"]
#define kOWDNightWeatherCodeCode602 [NSString stringWithFormat:@"\uf02a"]
#define kOWDNightWeatherCodeCode611 [NSString stringWithFormat:@"\uf026"]
#define kOWDNightWeatherCodeCode612 [NSString stringWithFormat:@"\uf026"]
#define kOWDNightWeatherCodeCode615 [NSString stringWithFormat:@"\uf026"]
#define kOWDNightWeatherCodeCode616 [NSString stringWithFormat:@"\uf026"]
#define kOWDNightWeatherCodeCode620 [NSString stringWithFormat:@"\uf026"]
#define kOWDNightWeatherCodeCode621 [NSString stringWithFormat:@"\uf02a"]
#define kOWDNightWeatherCodeCode622 [NSString stringWithFormat:@"\uf02a"]
#define kOWDNightWeatherCodeCode701 [NSString stringWithFormat:@"\uf029"]
#define kOWDNightWeatherCodeCode711 [NSString stringWithFormat:@"\uf062"]
#define kOWDNightWeatherCodeCode721 [NSString stringWithFormat:@"\uf0b6"]
#define kOWDNightWeatherCodeCode731 [NSString stringWithFormat:@"\uf063"]
#define kOWDNightWeatherCodeCode741 [NSString stringWithFormat:@"\uf04a"]
#define kOWDNightWeatherCodeCode761 [NSString stringWithFormat:@"\uf063"]
#define kOWDNightWeatherCodeCode762 [NSString stringWithFormat:@"\uf063"]
#define kOWDNightWeatherCodeCode781 [NSString stringWithFormat:@"\uf056"]
#define kOWDNightWeatherCodeCode800 [NSString stringWithFormat:@"\uf02e"]
#define kOWDNightWeatherCodeCode801 [NSString stringWithFormat:@"\uf022"]
#define kOWDNightWeatherCodeCode802 [NSString stringWithFormat:@"\uf022"]
#define kOWDNightWeatherCodeCode803 [NSString stringWithFormat:@"\uf022"]
#define kOWDNightWeatherCodeCode804 [NSString stringWithFormat:@"\uf086"]
#define kOWDNightWeatherCodeCode900 [NSString stringWithFormat:@"\uf056"]
#define kOWDNightWeatherCodeCode902 [NSString stringWithFormat:@"\uf073"]
#define kOWDNightWeatherCodeCode903 [NSString stringWithFormat:@"\uf076"]
#define kOWDNightWeatherCodeCode904 [NSString stringWithFormat:@"\uf072"]
#define kOWDNightWeatherCodeCode906 [NSString stringWithFormat:@"\uf024"]
#define kOWDNightWeatherCodeCode957 [NSString stringWithFormat:@"\uf050"]

@interface Icons : NSObject
    +(NSDictionary*)getIconsDictionary;
@end

#endif
